[project]
name = "memo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "BjÃ¶rn Bethge", email = "bjoern.bethge@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "core",
    "memvid>=0.1.3",
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.uv.sources]
core = { workspace = true }
